name = "igv"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-10"

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./api.mjs"  # dist/api.mjs

[durable_objects]
bindings = [
  { name = "rooms", class_name = "IGVRoom" },
]
